// Comprehensive Categories and Products Catalog Data for Olene Canto & Olene Foods

export const CATEGORIES_SHOWCASE = [
  {
    id: "biscuit-and-cookies",
    slug: "biscuit-and-cookies",
    title: "BISCUIT & COOKIES",
    subtitle: "Butter Fruit Biscuits, Egg Drops, Nut Bakes & Choco Crunch",
    description: "Handcrafted with 100% pure cultured butter, studded with candied fruits, roasted nuts, rich chocolate, and slow-baked to a melt-in-mouth golden crumb.",
    badge: "Bestseller Pantry",
    tagline: "100% Normandy Butter • 17 Signature Bakes",
    image: "/products/tutti-frutti-cookies-bowl.jpg",
    accentColor: "#9B1B22",
    items: [
      "Canto Nutty Buddy Roasted Cookies",
      "Canto Oatmeal Honey Raisin Cookies",
      "Glazed Confectionery Brioche Doughnuts",
      "Classic Tutti-Frutti Fruit Biscuits",
      "Artisan Fruit Butter Cookies",
      "Classic Heart Butter Shortbread",
      "Traditional Egg Biscuits (Coin Biscuits)",
      "Golden Butter Crunch Cookies",
      "Decadent Choco-Chip Cookies",
      "Round Butter Tea Biscuits",
      "Roasted Nut Butter Biscuits",
      "Pistachio Pinwheel Swirl Cookies",
      "Malabar Nankhatai Butter Drops",
      "Sugar-Glazed Tea Shortbread Biscuits",
      "Black Sesame Artisan Butter Biscuits",
    ],
  },
  {
    id: "sweet-and-mithai",
    slug: "sweet-and-mithai",
    title: "SWEET & MITHAI",
    subtitle: "Royal Khoya Pedas, Kesar Katli, Pure Ghee Mysore Pak, Halwa & Festive Ladoos",
    description: "Centuries of royal celebration heritage captured in rich pure cow ghee, slow-roasted gram flour, saffron, California almonds, Turkish figs, and handcrafted festive mithai.",
    badge: "Celebration Reserve",
    tagline: "100% Pure Desi Ghee • 20 Royal Creations",
    image: "/categories/sweet-and-mithai-showcase-v3.jpg",
    accentColor: "#C59B4B",
    items: [
      "Royal Festive Celebration Mithai Thali",
      "Traditional Pure Desi Ghee Mysore Pak",
      "Kesar Badam Triangle Katli Star Platter",
      "Royal Gajar Ka Halwa & Carrot Barfi",
      "Canto Royal Khoya Peda Luxury Tray",
      "Artisan Tutti-Frutti Mawa Barfi",
      "Sesame Crusted Date & Chocolate Rolls",
      "Royal Emerald Pistachio Dry Fruit Ladoos",
      "Kaju Alfonso Mango Miniature Delights",
      "Double Bowl Roasted Til & Nut Ladoos",
      "Twin Bowl Desi Ghee Boondi Ladoos",
      "Artisan Khajur Dry Fruit Barfi Cubes",
    ],
  },
  {
    id: "savory-snacks",
    slug: "savory-snacks",
    title: "SAVORY SNACKS",
    subtitle: "Malabar Nurukku, Cornflakes Mixture, Butter Murukku, Thattai & Coconut Macaroons",
    description: "Crispy, aromatic spices, and traditional stoneground savory crunch crafted using authentic coastal recipes and zero artificial additives.",
    badge: "Authentic Savory",
    tagline: "Everyday Tea-Time Companion • 9 Artisan Savories",
    image: "/categories/savory-bites.jpg",
    accentColor: "#8B4513",
    items: [
      "Olene Canto Malabar Nurukku",
      "Olene Canto Spicy Cornflakes Mixture",
      "Olene Canto Pure Butter Murukku Tub",
      "Olene Canto Herb & Masala Thattai Crackers",
      "Traditional Coconut Macaroons",
      "Mini Crispy Samosa Bites",
      "Traditional Spiral Murukku",
      "Crunchy Ring Murukku (Kodubale)",
      "Crispy Ribbon Pakoda",
    ],
  },

  {
    id: "breads-and-bakery",
    slug: "breads-and-bakery",
    title: "BREADS & BAKERY",
    subtitle: "Hearth Sliced Loaves, Luxury Plum Cakes, Hazelnut Brioche Doughnuts & Keepsake Tin Bakes",
    description: "Hearth-baked daily sliced breads, rich festive plum cakes, artisan hazelnut chocolate brioche doughnuts, sealed collectible fruit cake tins, and golden butter shortbread crafted fresh daily.",
    badge: "Hearth Bakery & Bakes",
    tagline: "Hearth-Baked Daily • 8 Handcrafted Bakes",
    image: "/categories/breads-and-bakery-showcase-v1.jpg",
    accentColor: "#8B4513",
    items: [
      "Artisan Daily Sliced White Loaf Bread",
      "Olene Canto Rich Spiced Plum Cake",
      "Artisan Hazelnut Chocolate Brioche Doughnuts",
      "Olene Canto Heritage Rich Fruit Cake",
      "Classic Golden Heart Butter Shortbread Cookies",
      "Twin Bowl Golden Honey-Glazed Doughnuts",
      "Olene Canto Sealed Soft Sweet Buns (Pack of 2)",
      "Artisan Coconut & Candied Fruit Sweet Bun",
    ],
  },
  {
    id: "whiteloaf-snacks",
    slug: "whiteloaf-snacks",
    title: "WHITELOAF SNACKS",
    subtitle: "Murukkus, Pakkavada, Thatta, Cheeda, Potato Crisps & Ragi Specials",
    description: "Authentic, wholesome packaged tea-time snacks by White Loaf Craft Bakers, featuring nice murukku, masala thatta, pakkavada, masala cheeda, onion murukku, potato crisps, and ragi specials.",
    badge: "White Loaf Brand",
    tagline: "Fresh & Tasty Retail Snack Packs",
    image: "/products/whiteloaf-nice-murukku.jpg",
    accentColor: "#D9222A",
    items: [
      "White Loaf Nice Murukku",
      "White Loaf Pakkavada",
      "White Loaf Masala Thatta",
      "White Loaf Ring Murukku",
      "White Loaf Masala Cheeda",
      "White Loaf Onion Murukku",
      "White Loaf Pudina Mixture",
      "White Loaf Potato Chilli",
      "White Loaf Butter Murukku",
      "White Loaf Potato Mixture Spicy",
      "White Loaf Ragi Murukku",
      "White Loaf Tomato Murukku",
      "White Loaf Sweet Mixture",
      "White Loaf Ragi Mixture",
    ],
  },
  {
    id: "whiteloaf-cookies",
    slug: "whiteloaf-cookies",
    title: "WHITELOAF COOKIES",
    subtitle: "Nutty Buddy, American Gold, Choco Chip, Butter Salt & Pure Ghee Cookies",
    description: "Artisan bakery cookies by White Loaf Craft Bakers, packaged in airtight presentation tins. Slow-baked using pure desi ghee, crunchy roasted nuts, wholesome oats, rich chocolate chips, and aromatic spices.",
    badge: "White Loaf Bakery",
    tagline: "A Taste to Remember Forever",
    image: "/products/whiteloaf-choco-chip-cookies.jpg",
    accentColor: "#8B0000",
    items: [
      "White Loaf Choco Chip Cookies",
      "White Loaf American Gold Cookies",
      "White Loaf Butter Salt Cookies",
      "White Loaf Nutty Buddy Cookies",
      "White Loaf Ghee Cookies",
      "White Loaf Oats Cookies",
      "White Loaf Curry Leaf Cookies",
      "White Loaf Masala Cookies",
    ],
  },
  {
    id: "whiteloaf-boxes",
    slug: "whiteloaf-boxes",
    title: "WHITELOAF BOXES",
    subtitle: "Sweet Gift Boxes, Ghee Pak, Dates Rolls, Badusha, Pedas, Laddus & Jilebi",
    description: "Exquisite celebratory sweet presentation boxes, sealed peda & laddu trays, dates rolls, and confectionery tubs by White Loaf Craft Bakers, featuring royal assorted sweets and authentic Kerala Kozhikodan halwa.",
    badge: "Celebration Reserve",
    tagline: "The Heavenly Source of Happiness",
    image: "/products/whiteloaf-premium-mixed-sweets-box.jpg",
    accentColor: "#1A1A1A",
    items: [
      "White Loaf Premium Mixed Sweets Box",
      "White Loaf Royal Mixed Sweets Box",
      "White Loaf Dates Roll Box",
      "White Loaf Ghee Pak Box",
      "White Loaf Badusha Box & Tray",
      "White Loaf Fresh Dates Roll Tray",
      "White Loaf Milk Sweets Box",
      "White Loaf Ghee Sweets Box",
      "White Loaf Milk Peda Box & Tray",
      "White Loaf Laddu Box & Tray",
      "White Loaf Jilebi Gift Box",
      "White Loaf Fresh Jilebi Tray",
      "White Loaf Mixed Sweets Box",
      "White Loaf Kozhikodan Mixed Halwa Tub",
    ],
  },
];

export const CATEGORY_PRODUCTS = {
  "biscuit-and-cookies": [
    {
      id: "canto-nutty-buddy-cookies",
      name: "Canto Nutty Buddy Roasted Cookies",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Signature Red Tin",
      weight: "350g Sealed Red Canister",
      price: "₹270",
      image: "/products/canto-nutty-buddy-studio.jpg",
      tagline: "Slow-Roasted Cashews, Peanuts & Pure Dairy Butter",
      description: "Our bestselling collectible red canister filled with crispy, aromatic cookies packed with double-roasted peanuts and creamy Malabar cashews for an addictive, deep golden nut crunch.",
      highlights: ["Signature Red Canister", "Double Roasted Cashews", "Pure White Studio Presentation"],
      ingredients: ["Roasted Cashews & Peanuts", "Pure Cultured Butter", "Demerara Sugar", "Stoneground Wheat"],
      calories: "165 kcal / cookie",
    },
    {
      id: "canto-oatmeal-honey-cookies",
      name: "Canto Oatmeal Honey Raisin Cookies",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Canister Tin Reserve",
      weight: "350g Sealed Luxury Tin",
      price: "₹260",
      image: "/products/canto-oatmeal-honey-studio.jpg",
      tagline: "Rolled Whole Oats, Wild Honey & Sun-Dried Raisins",
      description: "Packaged in our signature Olene Canto airtight silver canister: hearty whole rolled oats toasted in pure butter, sweetened with raw wild blossom honey, and loaded with chewy California seedless raisins.",
      highlights: ["Sealed Freshness Canister", "Raw Blossom Honey", "Whole Rolled Oats"],
      ingredients: ["Whole Rolled Oats", "Wild Mountain Honey", "California Raisins", "Normandy Butter", "Cinnamon"],
      calories: "140 kcal / cookie",
    },
    {
      id: "canto-glazed-brioche-doughnuts",
      name: "Glazed Confectionery Brioche Doughnuts",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Gourmet Platter",
      weight: "3 Pcs Artisanal Platter",
      price: "₹195",
      image: "/products/canto-glazed-doughnuts-platter.jpg",
      tagline: "Belgian Chocolate, Vanilla Cream & Salted Caramel Glaze",
      description: "An exquisite tea-time pastry platter featuring 3 gourmet brioche doughnuts glazed with decadent Belgian dark chocolate ganache, creamy ivory vanilla drizzle, and rich golden salted caramel on a pure white porcelain platter.",
      highlights: ["Belgian Chocolate Ganache", "Assorted Tri-Color Glaze", "Artisanal Platter Presentation"],
      ingredients: ["Pure Creamery Butter", "Belgian Dark & White Chocolate", "Salted Caramel Glaze", "Pasture Eggs", "Bourbon Vanilla"],
      calories: "185 kcal / piece",
    },
    {
      id: "tutti-frutti-slice",
      name: "Classic Tutti-Frutti Fruit Biscuits",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Heritage Bestseller",
      weight: "250g / 500g Pack",
      price: "₹180",
      image: "/products/tutti-frutti-slice-biscuits.jpg",
      tagline: "Jeweled Candied Fruits & Pure Butter",
      description: "Our signature Karachi-style fruit biscuits, delicately rectangular and hand-sliced, studded with ruby and emerald candied papaya fruits, cardamom notes, and a crumbly, melt-in-mouth butter texture.",
      highlights: ["100% Pure Butter", "Cardamom Aroma", "Zero Preservatives"],
      ingredients: ["Normandy Cultured Butter", "Candied Tutti Frutti", "Cardamom & Vanilla", "Fine Stoneground Wheat"],
      calories: "140 kcal / 2 pcs",
    },
    {
      id: "fruit-butter-cookies",
      name: "Artisan Fruit Butter Cookies",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Tea-Time Classic",
      weight: "300g Tin / Bowl",
      price: "₹200",
      image: "/products/tutti-frutti-cookies-bowl.jpg",
      tagline: "Golden Baked Candied Fruit Delights",
      description: "Golden-baked all-butter cookies loaded with generous bits of candied fruits and rich vanilla essence. Crisp on the outside with a velvety, crumbly bite that pairs perfectly with warm afternoon tea.",
      highlights: ["Tableware Ready", "Rich Candied Papaya", "Slow Baked"],
      ingredients: ["Cultured Dairy Butter", "Candied Papaya & Cherries", "Vanilla Pod Essence", "Cane Sugar"],
      calories: "150 kcal / 2 pcs",
    },
    {
      id: "egg-coin-biscuits",
      name: "Traditional Egg Biscuits (Coin Biscuits)",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Nostalgic Favorite",
      weight: "200g / 400g Pack",
      price: "₹150",
      image: "/products/classic-egg-coin-biscuits.jpg",
      tagline: "Light, Airy & Nostalgic Vintage Bakes",
      description: "A beloved bakery heritage classic across South India: delicate, bite-sized golden coin drops baked with farm-fresh eggs, gentle cane sugar, and pure Madagascar vanilla that dissolve effortlessly on the tongue.",
      highlights: ["Farm-Fresh Eggs", "Light & Airy Texture", "Zero Artificial Colors"],
      ingredients: ["Farm Fresh Eggs", "Madagascar Vanilla", "Wheat Flour", "Gentle Cane Sugar"],
      calories: "110 kcal / serving",
    },
    {
      id: "golden-butter-cookies",
      name: "Golden Butter Crunch Cookies",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Artisan Reserve",
      weight: "250g Gift Tin",
      price: "₹220",
      image: "/products/golden-butter-crunch-cookies.jpg",
      tagline: "Amber Crinkled Butter Shortbread",
      description: "Rustic, crinkle-topped artisan butter cookies crafted with generous churns of pure cultured dairy butter, toasted wheat aromas, and a delicate sprinkle of sea-salt crystals for the ultimate deep crunch.",
      highlights: ["Pure Normandy Butter", "Golden Crinkle Crust", "Delicate Fleur de Sel"],
      ingredients: ["100% Normandy Butter", "Caramelized Sugar Crumb", "Fleur de Sel", "Slow-Roasted Flour"],
      calories: "160 kcal / 2 pcs",
    },
    {
      id: "round-butter-tea-biscuits",
      name: "Round Butter Tea Shortbread Biscuits",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Everyday Masterpiece",
      weight: "250g / 500g Stack Pack",
      price: "₹195",
      image: "/products/round-butter-tea-biscuits.jpg",
      tagline: "Artisan Fork-Pitted Butter Shortbread Rounds",
      description: "Golden, oven-baked round shortbread biscuits stacked with rich cultured butter aromas, delicate fork pricks, and a savory-sweet crumble that melts instantly when dipped in morning tea.",
      highlights: ["100% Cultured Butter", "Golden Oven Baked", "Classic Tea Companion"],
      ingredients: ["Normandy Cultured Butter", "Stoneground Wheat Flour", "Fleur de Sel & Cane Sugar", "Madagascar Vanilla"],
      calories: "145 kcal / 2 pcs",
    },
    {
      id: "belgian-choco-chip-cookies",
      name: "Decadent Choco-Chip Cookies",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Chef's Signature",
      weight: "250g Deluxe Pack",
      price: "₹240",
      image: "/products/belgian-choco-chip-cookies.jpg",
      tagline: "Deep Cocoa Crumb & Rich Chocolate Chunks",
      description: "Richly baked cookies boasting deep cocoa undertones, lavishly studded with premium dark chocolate chips that deliver a satisfying crisp bite followed by molten chocolate decadence in every mouthful.",
      highlights: ["Belgian Dark Chocolate", "Dutch Processed Cacao", "Slow-Fermented Dough"],
      ingredients: ["Belgian Dark Chocolate 60%", "Dutch Processed Cocoa", "Pure Creamery Butter", "Brown Cane Sugar"],
      calories: "175 kcal / cookie",
    },
    {
      id: "roasted-nut-butter-biscuits",
      name: "Roasted Nut Butter Biscuits",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Nutty Crunch",
      weight: "250g / 500g Pack",
      price: "₹210",
      image: "/products/roasted-nut-butter-biscuits.jpg",
      tagline: "Golden Roasted Peanuts & Creamy Cashews",
      description: "Thick-cut rectangular shortbread biscuits packed with golden roasted peanuts and crushed cashews. Offers a rich, savory-sweet nuttiness and a satisfying crumbly crunch in every bite.",
      highlights: ["Slow Roasted Peanuts", "Creamy Cashew Bits", "Pure Butter Base"],
      ingredients: ["Roasted Peanuts & Cashews", "Normandy Butter", "Stoneground Wheat", "Cane Sugar"],
      calories: "165 kcal / 2 pcs",
    },
    {
      id: "pista-pinwheel-swirl-cookies",
      name: "Pistachio Pinwheel Swirl Cookies",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Atelier Festive",
      weight: "300g Luxury Tray / Box",
      price: "₹250",
      image: "/products/pista-pinwheel-swirl-cookies.jpg",
      tagline: "Emerald Pistachio & Vanilla Swirl",
      description: "Artisanal dual-tone pinwheel cookies featuring alternating spirals of pure pistachio butter dough and sweet Madagascar vanilla. Hand-rolled, chilled, and sliced for a stunning presentation.",
      highlights: ["Dual-Tone Pinwheel", "Pistachio Essence", "Festive Tea-Time"],
      ingredients: ["Sicilian Pistachio Paste", "Cultured Butter", "Madagascar Vanilla", "Unbleached Flour"],
      calories: "145 kcal / 2 pcs",
    },
    {
      id: "malabar-nankhatai-butter-drops",
      name: "Malabar Nankhatai Butter Drops",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Heritage Classic",
      weight: "300g Ceramic Bowl / Tin",
      price: "₹190",
      image: "/products/malabar-nankhatai-butter-drops.jpg",
      tagline: "Melt-in-Mouth Spiced Cardamom Crumb",
      description: "Traditional Indian shortbread cookies baked to a golden dome with a tender, melt-on-the-tongue texture. Infused with aromatic green cardamom and clarified pure butter for authentic nostalgia.",
      highlights: ["Melt-in-Mouth Texture", "Green Cardamom", "Traditional Ghee & Butter"],
      ingredients: ["Pure Clarified Ghee & Butter", "Roasted Gram Flour", "Green Cardamom", "Fine Semolina"],
      calories: "135 kcal / 2 pcs",
    },
    {
      id: "sugar-crystal-tea-biscuits",
      name: "Sugar-Glazed Tea Shortbread Biscuits",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Tea-Time Favorite",
      weight: "250g / 500g Pack",
      price: "₹170",
      image: "/products/sugar-crystal-tea-biscuits.jpg",
      tagline: "Fork-Pressed Crust & Sparkling Sugar Crystals",
      description: "Classic tea-room shortbread rounds pressed with signature artisan fork ridges and dusted with sparkling crystalline sugar. Crispy edges and a rich, buttery center made for dipping into steaming hot tea.",
      highlights: ["Sparkling Sugar Crust", "Classic Fork Marks", "Perfect Chai Companion"],
      ingredients: ["Normandy Cultured Butter", "Crystalline Sugar Glaze", "Fine Wheat Flour", "Sea Salt"],
      calories: "130 kcal / 2 pcs",
    },
    {
      id: "black-sesame-butter-biscuits",
      name: "Black Sesame Artisan Butter Biscuits",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Aromatic Crunch",
      weight: "250g Artisan Tin",
      price: "₹200",
      image: "/products/black-sesame-butter-biscuits.jpg",
      tagline: "Toasted Black Sesame & Golden Dairy Butter",
      description: "Delicately crisp round butter biscuits speckled generously with toasted black sesame seeds (til). The nuttiness of roasted sesame pairs flawlessly with slow-baked dairy butter for an earthy, sophisticated aroma.",
      highlights: ["Toasted Black Sesame", "Earthy Nutty Aroma", "Delicate Crisp Snap"],
      ingredients: ["Toasted Black Sesame Seeds", "Cultured Creamery Butter", "Stoneground Wheat", "Raw Cane Sugar"],
      calories: "140 kcal / 2 pcs",
    },
    {
      id: "heart-butter-cookies",
      name: "Classic Heart Butter Shortbread Cookies",
      category: "biscuit-and-cookies",
      categoryName: "Biscuit & Cookies",
      badge: "Atelier Signature",
      weight: "250g / 500g Stack Pack",
      price: "₹210",
      image: "/products/heart-butter-cookies.jpg",
      tagline: "Iconic Heart-Cut Cultured Butter Shortbread",
      description: "Our signature romantic bake: rich, velvety all-butter shortbread cut into iconic heart shapes with delicate golden edges and a tender melt-in-mouth crumb that honors traditional European tea salons.",
      highlights: ["100% Normandy Butter", "Heart-Cut Artisan Bakes", "Melt-in-Mouth Crumb"],
      ingredients: ["Normandy Cultured Butter", "Fine Stoneground Wheat", "Pure Cane Sugar", "Madagascar Vanilla"],
      calories: "145 kcal / 2 pcs",
    },
  ],

  "sweet-and-mithai": [
    {
      id: "mithai-thali-festive-assortment",
      name: "Royal Festive Celebration Mithai Thali",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Royal Platter",
      weight: "500g Deluxe Plate",
      price: "₹450",
      image: "/products/royal-festive-mithai-thali-platter.jpg",
      tagline: "Silver Vark Pedas, Fruit Marzipan, Pistachio Rolls & Golden Ladoos",
      description: "A majestic celebration platter laden with artisanal festive sweets: silver-foil khoya pedas, hand-sculpted apple marzipan, pistachio mawa rolls, golden motichoor ladoo, and layered chocolate burfi.",
      highlights: ["Pure Silver Vark", "Handmade Fruit Marzipan", "Festive Centerpiece"],
      ingredients: ["Full Cream Khoya", "Cashew Paste", "Desi Cow Ghee", "Edible Silver Vark", "Saffron & Cardamom"],
      calories: "165 kcal / piece avg",
    },
    {
      id: "tutti-frutti-milk-cake-squares",
      name: "Artisan Tutti-Frutti Mawa Barfi Squares",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Confectionery Special",
      weight: "9 Pcs (300g Tray)",
      price: "₹240",
      image: "/products/tutti-frutti-milk-cake-squares-v3.jpg",
      tagline: "Cardamom Khoya Fudge Studded with Candied Fruit Drops",
      description: "Tender, melt-in-mouth milk mawa squares infused with crushed cardamom and studded with ruby, emerald, and amber candied papaya morsels in an elegant presentation tray.",
      highlights: ["Full Cream Milk Mawa", "Candied Fruit Drops", "Melt-In-Mouth Texture"],
      ingredients: ["Simmered Cow Milk Khoya", "Candied Papaya (Tutti Frutti)", "Desi Ghee", "Green Cardamom", "Cane Sugar"],
      calories: "140 kcal / piece",
    },
    {
      id: "sesame-chocolate-date-rolls",
      name: "Sesame Crusted Date & Chocolate Khajur Rolls",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Naturally Sweetened",
      weight: "250g / 500g Tray",
      price: "₹320",
      image: "/products/sesame-chocolate-date-rolls-v3.jpg",
      tagline: "Medjool Dates, Toasted Sesame & Crunchy Nut Center",
      description: "Artisan chocolate and dark Medjool date rolls densely rolled in toasted golden sesame seeds, packed with whole California walnuts, cashews, and pistachios.",
      highlights: ["Zero Added Sugar", "Medjool Dates & Dark Cocoa", "Whole California Walnuts"],
      ingredients: ["Medjool Dates (Khajur)", "Roasted White Sesame Seeds", "Dutch Dark Cocoa", "Walnuts & Cashews", "Desi Ghee"],
      calories: "135 kcal / piece",
    },
    {
      id: "til-gond-dryfruit-ladoos",
      name: "Double Bowl Roasted Til & Winter Dry Fruit Ladoos",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Winter Special",
      weight: "300g Dual Bowl Pack",
      price: "₹260",
      image: "/products/til-gond-dryfruit-ladoos-v3.jpg",
      tagline: "Golden Roasted Sesame, Gond & Crunchy Nut Halves",
      description: "Wholesome festive ladoos hand-rolled with slow-roasted white sesame seeds, crunchy edible gum (gond), crushed California almonds, and organic jaggery.",
      highlights: ["Organic Palm Jaggery", "Edible Gum (Gond)", "Roasted Sesame Seeds"],
      ingredients: ["White Sesame Seeds", "Organic Jaggery", "Edible Gum (Gond)", "California Almonds", "Desi Ghee"],
      calories: "150 kcal / ladoo",
    },
    {
      id: "til-rewari-puffed-crunch-stack",
      name: "Heritage Til Rewari & Puffed Grain Crunch Rounds",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Heritage Crunch",
      weight: "250g Tower Pack",
      price: "₹190",
      image: "/products/til-rewari-sesame-stack.jpg",
      tagline: "Golden Cane Jaggery & Aromatic Toasted Sesame Coins",
      description: "Crisp, golden caramel discs coated with aromatic toasted sesame seeds and puffed grain pearls, slow-crafted over open brass pans for the nostalgic winter crunch.",
      highlights: ["Traditional Open Pan Cooked", "Caramelized Jaggery", "Nostalgic Winter Snack"],
      ingredients: ["Roasted Sesame Seeds", "Pure Cane Jaggery", "Cardamom Infusion", "Ghee Glaze"],
      calories: "115 kcal / piece",
    },
    {
      id: "golden-ghee-boondi-ladoos",
      name: "Twin Bowl Desi Ghee Boondi Ladoos",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Temple Classic",
      weight: "350g Dual Bowl Pack",
      price: "₹220",
      image: "/products/golden-ghee-boondi-ladoos-v3.jpg",
      tagline: "Pure Desi Ghee Gram Pearls, Melon Seeds & Saffron",
      description: "A royal celebratory favorite: delicate golden boondi pearls fried in 100% pure desi cow ghee, scented with saffron, roasted melon seeds (magaz), and warm green cardamom.",
      highlights: ["100% Desi Cow Ghee", "Crunchy Melon Seeds", "Slow-Fried Gram Pearls"],
      ingredients: ["Bengal Gram Besan", "Desi Cow Ghee", "Kashmir Saffron", "Melon Seeds (Magaz)", "Cardamom"],
      calories: "175 kcal / ladoo",
    },
    {
      id: "kaju-mango-marzipan-tray",
      name: "Kaju Alfonso Mango Miniature Delights",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Chef's Masterpiece",
      weight: "12 Pcs Presentation Tray",
      price: "₹295",
      image: "/products/kaju-mango-marzipan-tray.jpg",
      tagline: "Hand-Sculpted Alfonso Cashew Marzipan with Pistachio Leaves",
      description: "Artisanal mango-shaped confections handcrafted from 100% premium cashew nut marzipan infused with real Ratnagiri Alfonso mango puree and topped with edible pistachio leaves in fluted paper cups.",
      highlights: ["100% Goan Cashew Paste", "Real Alfonso Mango Pulp", "Hand-Sculpted Artistry"],
      ingredients: ["Goan Cashew Nut Paste", "Alfonso Mango Puree", "Cane Sugar", "Natural Plant Extract Colors"],
      calories: "145 kcal / piece",
    },
    {
      id: "pista-dryfruit-katori-ladoos",
      name: "Royal Emerald Pistachio Dry Fruit Ladoos",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Royal Reserve",
      weight: "6 Pcs (250g Tray)",
      price: "₹350",
      image: "/products/pista-dryfruit-katori-ladoos-v3.jpg",
      tagline: "Sicilian Green Pistachios, Saffron Cream & Almond Core",
      description: "Six royal spherical confections encrusted in crushed Sicilian emerald pistachios and roasted almond slivers, crowned with a dark chocolate mawa bud.",
      highlights: ["Crushed Emerald Pistachios", "Rich Nut Core", "Patisserie Fluted Cups"],
      ingredients: ["Sicilian Pistachios", "California Almonds", "Mawa Fudge", "Pure Desi Ghee", "Saffron Essence"],
      calories: "165 kcal / piece",
    },
    {
      id: "kesar-badam-triangle-katli",
      name: "Artisan Kesar Badam Triangle Katli Star Platter",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Festive Signature",
      weight: "300g / 600g Platter",
      price: "₹280",
      image: "/products/kesar-badam-triangle-star-platter.jpg",
      tagline: "Pure Saffron Almond Diamonds in Starburst Presentation",
      description: "Geometric triangular barfi crafted from finely ground California almonds and pure saffron essence, garnished with whole sliced almonds and slow-toasted in clarified butter.",
      highlights: ["Finely Ground Almonds", "Kashmiri Saffron", "Starburst Presentation"],
      ingredients: ["California Almond Flour", "Pure Desi Ghee", "Saffron Strands", "Raw Sugar", "Cardamom"],
      calories: "150 kcal / piece",
    },
    {
      id: "saffron-coconut-motichoor-ladoos",
      name: "Saffron Motichoor & Coastal Coconut Ladoos",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Celebration Favorite",
      weight: "6 Pcs (300g Pack)",
      price: "₹210",
      image: "/products/saffron-coconut-motichoor-cups.jpg",
      tagline: "Saffron Boondi Pearls Coated in Toasted Coconut Flakes",
      description: "Delicate micro-boondi pearls simmered in pure saffron cardamom syrup, rolled by hand into spheres, crowned with a toasted almond sliver, and dusted in snow coconut flakes.",
      highlights: ["Toasted Coastal Coconut", "Fine Saffron Boondi", "Paper-Cup Presentation"],
      ingredients: ["Gram Flour Micro Boondi", "Fresh Desi Ghee", "Desiccated Coconut", "Kashmir Saffron", "Almond Topping"],
      calories: "170 kcal / piece",
    },
    {
      id: "royal-dryfruit-barfi-stack",
      name: "Royal Dry Fruit Halwa & Nut Barfi Stack",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Nut Reserve",
      weight: "300g / 600g Pack",
      price: "₹310",
      image: "/products/royal-dryfruit-barfi-stack.jpg",
      tagline: "Whole Almonds, Cashews & Emerald Pistachios in Ghee Fudge",
      description: "Three thick-cut tiers of rich chewy halwa fudge packed with whole California almonds, cashew halves, and green pistachios, simmered in pure desi cow ghee.",
      highlights: ["Loaded with Whole Nuts", "Slow-Caramelized Ghee", "Energy Rich Delicacy"],
      ingredients: ["Whole Roasted Almonds & Pistachios", "Cashew Paste", "Desi Ghee", "Demerara Sugar", "Nutmeg"],
      calories: "195 kcal / square",
    },
    {
      id: "mysore-pak-twin-towers",
      name: "Traditional Pure Desi Ghee Mysore Pak",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Royal Masterpiece",
      weight: "4 Pcs / 400g Pack",
      price: "₹260",
      image: "/products/mysore-pak-pure-ghee-stack.jpg",
      tagline: "Melt-in-Mouth Porous Desi Ghee Honeycomb Besan Bars",
      description: "Lavish golden honeycomb bars slow-cooked with aromatic roasted besan and molten pure desi cow ghee that dissolves instantaneously upon the palate.",
      highlights: ["100% Pure Cow Ghee", "Honeycomb Porous Crumb", "Royal Mysore Heritage"],
      ingredients: ["Bengal Gram Flour (Besan)", "100% Pure Desi Cow Ghee", "Clarified Sugar Syrup", "Cardamom Aroma"],
      calories: "210 kcal / bar",
    },
    {
      id: "royal-deluxe-mithai-thali",
      name: "Royal Deluxe Tasting Platter (Assorted Mithai)",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Tasting Platter",
      weight: "500g Deluxe Thali Box",
      price: "₹420",
      image: "/products/royal-deluxe-mithai-thali-v3.jpg",
      tagline: "Curated Collection of Canto Signature Royal Mithai",
      description: "A round festive presentation platter laden with silver-vark peda, apple marzipan, two-tone chocolate barfi, golden motichoor ladoo, and walnut halwa.",
      highlights: ["7 Signature Mithai Varieties", "Pure Silver Vark", "Festive Tasting Selection"],
      ingredients: ["Full Cream Khoya", "Cashew Marzipan", "Pure Desi Ghee", "Edible Silver Vark", "Cocoa & Rose Extract"],
      calories: "165 kcal / piece avg",
    },
    {
      id: "hollow-khoya-wafer-rolls",
      name: "Artisan Crispy Khoya & Sesame Wafer Rolls",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Atelier Creation",
      weight: "8 Pcs (300g Platter)",
      price: "₹270",
      image: "/products/hollow-khoya-wafer-rolls-v3.jpg",
      tagline: "Crispy Roasted Wafer Tubes Filled with Dark Mawa Fudge",
      description: "A pyramid of golden, slow-baked crispy wafer rolls filled with spiced chocolate mawa fudge and dusted with aromatic toasted sesame seeds.",
      highlights: ["Crisp Wafer Shell", "Velvety Khoya Center", "Sesame Seed Coating"],
      ingredients: ["Crisp Wafer Shell", "Simmered Khoya Fudge", "Toasted Sesame Seeds", "Dutch Cocoa", "Cardamom"],
      calories: "155 kcal / roll",
    },
    {
      id: "canto-royal-khoya-peda-tray",
      name: "Canto Royal Khoya Peda Luxury Tray",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Heritage Gold",
      weight: "14 Pcs (400g Tray)",
      price: "₹320",
      image: "/products/canto-royal-khoya-peda-tray.jpg",
      tagline: "Full-Cream Slow-Simmered Khoya Pedas with Roasted Pistachio Crowns",
      description: "Velvety milk pedas slow-simmered from full-cream cow milk khoya, stamped with royal saffron rings, and crowned with whole roasted pistachio halves in individual fluted cups in an elegant presentation tray.",
      highlights: ["14-Piece Presentation Tray", "Full Cream Khoya", "Pistachio & Saffron Crown"],
      ingredients: ["Farm Fresh Milk Khoya", "Cane Sugar", "Green Cardamom Powder", "Roasted Pistachios", "Saffron"],
      calories: "135 kcal / peda",
    },
    {
      id: "heritage-assorted-mithai-plate",
      name: "Heritage Festive Assorted Mithai Plate",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Festive Assortment",
      weight: "450g Tasting Dish",
      price: "₹380",
      image: "/products/heritage-assorted-mithai-plate-v3.jpg",
      tagline: "Kaju Katli, Besan Barfi, Date Halwa & Festive Modak",
      description: "A festive tasting dish featuring golden besan barfi, silver-vark kaju katli, boondi ladoo, dark date halwa, and an artisan floral modak confection.",
      highlights: ["Authentic Temple Sweets", "Festive Floral Modak", "Pure Ghee Preparations"],
      ingredients: ["Besan & Ghee", "Cashew Paste", "Medjool Dates", "Cardamom", "Edible Silver Foil"],
      calories: "160 kcal / piece avg",
    },
    {
      id: "golden-honey-crunch-cookies",
      name: "Artisan Golden Honey Butter Crunch Cookies",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Bakery Special",
      weight: "5 Pcs (300g Stack)",
      price: "₹210",
      image: "/products/golden-honey-crunch-cookies.jpg",
      tagline: "Honey-Glazed Cornflake Cluster & Pure Butter Cookies",
      description: "Cluster stack of thick, oven-cracked golden cookies coated with honey-glazed cornflake crunch and slow-baked creamery butter for supreme afternoon tea crunch.",
      highlights: ["Honey Glazed Cornflakes", "Slow-Caramelized Butter", "Cracked Golden Dome"],
      ingredients: ["Normandy Butter", "Wild Blossom Honey", "Crisp Cornflakes", "Stoneground Wheat Flour"],
      calories: "155 kcal / cookie",
    },
    {
      id: "gajar-halwa-carrot-barfi",
      name: "Royal Gajar Ka Halwa & Carrot Barfi Stack",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Farm Fresh Winter",
      weight: "4 Slices (350g Stack)",
      price: "₹290",
      image: "/products/royal-gajar-halwa-carrot-stack.jpg",
      tagline: "Slow-Simmered Winter Carrots, Khoya & Desi Cow Ghee",
      description: "Four thick slices of vibrant crimson winter carrot halwa simmered for 8 hours in whole milk, desi cow ghee, and cardamom, garnished with whole fresh farm carrots.",
      highlights: ["8-Hour Slow Cooked", "Winter Red Carrots", "Desi Cow Ghee & Khoya"],
      ingredients: ["Fresh Red Carrots", "Desi Cow Ghee", "Whole Milk Khoya", "Green Cardamom", "California Almonds"],
      calories: "180 kcal / slice",
    },
    {
      id: "walnut-dryfruit-halwa-squares",
      name: "Royal Walnut & Pistachio Halwa Fudge Squares",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Nut Reserve",
      weight: "3 Slices (300g Pack)",
      price: "₹330",
      image: "/products/walnut-dryfruit-halwa-squares-v3.jpg",
      tagline: "Kashmiri Walnuts, Whole Almonds & Pure Ghee Fudge",
      description: "Three thick-cut squares of dense, caramelized dry fruit halwa studded with chunky Kashmiri walnuts, roasted almonds, and slivered pistachios.",
      highlights: ["Kashmiri Walnuts", "Whole Roasted Almonds", "Slow Ghee Caramelization"],
      ingredients: ["Kashmiri Walnuts", "California Almonds", "Pistachios", "Desi Ghee", "Demerara Sugar"],
      calories: "205 kcal / square",
    },
    {
      id: "khajur-dryfruit-halwa-bowl",
      name: "Artisan Khajur Dry Fruit Barfi Cubes Bowl",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Zero Added Sugar",
      weight: "300g Porcelain Bowl",
      price: "₹340",
      image: "/products/khajur-dryfruit-halwa-bowl-v3.jpg",
      tagline: "Arabian Dates, Roasted Cashews & California Almond Cubes",
      description: "A sleek black bowl filled with rich, chewy bite-sized cubes of naturally sweetened Arabian date fudge loaded with crunchy California cashews and almonds.",
      highlights: ["100% Natural Dates", "No Added Refined Sugar", "Generous Cashew Chunks"],
      ingredients: ["Arabian Black Dates", "Roasted Cashews", "California Almonds", "Desi Ghee", "Cardamom"],
      calories: "145 kcal / cube",
    },
    {
      id: "canto-royal-peda-gold-box",
      name: "Canto Royal Khoya Peda Gold Gift Box",
      category: "sweet-and-mithai",
      categoryName: "Sweet & Mithai",
      badge: "Luxury Gift Box",
      weight: "30 Pcs (600g Box)",
      price: "₹420",
      image: "/products/canto-royal-peda-gold-box-30pc.jpg",
      tagline: "Luxury 30-Piece Golden Celebration Box with Royal Canto Seal",
      description: "Handcrafted from pure full-fat farm milk slow-simmered into velvety khoya, infused with green cardamom, and crowned with whole roasted almond slices in individual pleated cups with royal Canto seals.",
      highlights: ["30-Piece Gold Gift Box", "Full Cream Khoya", "Pure Cow Milk"],
      ingredients: ["Farm Fresh Milk Khoya", "Refined Cane Sugar", "Green Cardamom Powder", "Roasted California Almonds"],
      calories: "135 kcal / peda",
    },
  ],

  "white-loaf": [
    {
      id: "classic-white-loaf-bread",
      name: "Daily Sliced White Loaf Bread",
      category: "white-loaf",
      categoryName: "White Loaf Wholesale",
      badge: "Everyday Staple",
      weight: "400g Sliced Loaf",
      price: "₹55",
      image: "/products/classic-white-loaf-bread.jpg",
      tagline: "Soft Crumb, Golden Crust & Oven-Fresh Everyday",
      description: "Our signature sandwich bread baked daily with unbleached flour, gentle sweetness, and an ultra-soft crumb. Sliced uniformly for retail sandwich counters, cafes, and home breakfast tables.",
      highlights: ["Daily Hearth Baked", "Soft Pillowy Crumb", "Uniform Sandwich Slices"],
      ingredients: ["Unbleached Wheat Flour", "Purified Water", "Live Baker's Yeast", "Sea Salt", "Vegetable Shortening"],
      calories: "80 kcal / slice",
    },
    {
      id: "multigrain-seeded-bread",
      name: "Multigrain & Seeded Sandwich Loaf",
      category: "white-loaf",
      categoryName: "White Loaf Wholesale",
      badge: "Nutri Bakes",
      weight: "400g Loaf",
      price: "₹75",
      image: "/categories/fruit-biscuits.jpg",
      tagline: "7 Sprouted Grains, Flax, Oats & Sunflower Seeds",
      description: "Wholesome, fiber-dense sandwich loaf encrusted with toasted sunflower seeds, golden flax, and rolled oats for a hearty breakfast sandwich.",
      highlights: ["7 Ancient Grains", "High Fiber", "No Preservatives"],
      ingredients: ["Sprouted Wheat Flour", "Rolled Oats", "Flaxseed", "Sunflower Seeds", "Malted Barley"],
      calories: "95 kcal / slice",
    },
    {
      id: "artisan-brioche-burger-buns",
      name: "Commercial Brioche Burger Buns (Pack of 4)",
      category: "white-loaf",
      categoryName: "White Loaf Wholesale",
      badge: "Foodservice Choice",
      weight: "4 Pcs (320g)",
      price: "₹80",
      image: "/products/white-loaf-doughnut.jpg",
      tagline: "Rich Egg-Washed Brioche with Sesame Topping",
      description: "Plump, golden brioche buns with a featherlight interior and glossy egg wash, engineered specifically to hold gourmet patties without sogginess.",
      highlights: ["Golden Egg Wash", "Featherlight Crumb", "Cafe Grade"],
      ingredients: ["Enriched Wheat Flour", "Pasture Eggs", "Pure Creamery Butter", "Toasted Sesame", "Cane Sugar"],
      calories: "190 kcal / bun",
    },
  ],

  "savory-snacks": [
    {
      id: "canto-malabar-nurukku",
      name: "Olene Canto Malabar Nurukku",
      category: "savory-snacks",
      categoryName: "Savory Snacks",
      badge: "Authentic Malabar",
      weight: "200g Fresh Retail Pouch",
      price: "₹110",
      image: "/products/canto-malabar-nurukku-pouch.jpg",
      tagline: "Traditional Kerala Spiced Rice Murukku Pouch",
      description: "Our signature retail packaged Malabar Nurukku, crafted following authentic North Kerala recipes with stoneground rice flour, toasted black sesame, and aromatic cumin, delivering an irresistible festive snap.",
      highlights: ["Authentic Malabar Recipe", "Aroma of Black Sesame", "Sealed Freshness Pouch"],
      ingredients: ["Stoneground Rice Flour", "Toasted Black Sesame", "Roasted Cumin", "Pure Sea Salt", "Refined Vegetable Oil"],
      calories: "130 kcal / 30g",
    },
    {
      id: "canto-cornflakes-mixture",
      name: "Olene Canto Spicy Cornflakes Mixture",
      category: "savory-snacks",
      categoryName: "Savory Snacks",
      badge: "Tea-Time Crunch",
      weight: "200g / 400g Pack",
      price: "₹140",
      image: "/products/canto-cornflakes-mixture.jpg",
      tagline: "Golden Cornflakes, Roasted Peanuts & Savory Sev",
      description: "A crunchy, savory tea-time medley of slow-roasted golden cornflakes, crunchy fried peanuts, fragrant curry leaves, and delicately spiced gram flour sev tossed in a signature coastal spice blend.",
      highlights: ["Crunchy Cornflakes", "Roasted Peanuts", "Double-Bowl Presentation"],
      ingredients: ["Golden Cornflakes", "Fried Peanuts", "Gram Flour Sev", "Curry Leaves", "Chili & Turmeric Blend", "Cold-Pressed Oil"],
      calories: "145 kcal / 30g",
    },
    {
      id: "canto-butter-murukku-tub",
      name: "Olene Canto Pure Butter Murukku Tub",
      category: "savory-snacks",
      categoryName: "Savory Snacks",
      badge: "Butter Special",
      weight: "200g Sealed Deli Tub",
      price: "₹145",
      image: "/products/canto-butter-murukku-tub.jpg",
      tagline: "Melt-in-Mouth Golden Rice Coils Infused with Dairy Butter",
      description: "Delicately hand-extruded golden coils prepared from premium rice flour, roasted gram, and churned dairy butter that shatters into a rich, melt-in-the-mouth savory crunch in every bite.",
      highlights: ["Pure Dairy Butter", "Delicate Coiled Texture", "Fresh Sealed Tub"],
      ingredients: ["Rice Flour", "Roasted Urad Flour", "Cultured Dairy Butter", "White Sesame", "Asafoetida", "Cold-Pressed Sunflower Oil"],
      calories: "140 kcal / 30g",
    },
    {
      id: "canto-herb-masala-thattai",
      name: "Olene Canto Herb & Masala Thattai Crackers",
      category: "savory-snacks",
      categoryName: "Savory Snacks",
      badge: "Artisan Savory",
      weight: "250g Stack Pack",
      price: "₹160",
      image: "/products/canto-herb-masala-thattai.jpg",
      tagline: "Handcrafted Herb-Crusted Savory Discs with Toasted Spices",
      description: "Hearty, thick-cut savory shortbread discs infused with fresh aromatic curry leaves, green coriander, cracked cumin, and mild red chili flakes, baked to a deep golden, crumbly crunch.",
      highlights: ["Fresh Curry Leaves", "Toasted Spices", "Golden Herb Crust"],
      ingredients: ["Stoneground Wheat", "Roasted Gram Flour", "Fresh Curry Leaves", "Cold-Pressed Oil", "Cracked Cumin & Chili", "Sea Salt"],
      calories: "135 kcal / piece",
    },
    {
      id: "canto-coconut-macaroons",
      name: "Traditional Coconut Macaroons",
      category: "savory-snacks",
      categoryName: "Savory Snacks",
      badge: "Bakery Classic",
      weight: "250g / 500g Pack",
      price: "₹180",
      image: "/products/canto-coconut-macaroons.jpg",
      tagline: "Crisp Peaked Amber Crust with Chewy Coconut Crumb",
      description: "Iconic South Indian bakery tea-time specialty: slow-baked golden coconut drops with a delicate amber crisp exterior and a tender, melt-in-the-mouth crumb packed with fresh coastal coconut shreds.",
      highlights: ["100% Coastal Coconut", "Crisp Peaked Tips", "No Artificial Essence"],
      ingredients: ["Desiccated Coconut", "Pasture Egg Whites", "Pure Cane Sugar", "Madagascar Vanilla"],
      calories: "125 kcal / piece",
    },
    {
      id: "savory-crispy-samosa-bites",
      name: "Mini Crispy Samosa Bites",
      category: "savory-snacks",
      categoryName: "Savory Snacks",
      badge: "Snack Favorite",
      weight: "200g Tub",
      price: "₹120",
      image: "/products/savory-crispy-samosa-bites.jpg",
      tagline: "Flaky Golden Triangles with Spiced Lentil Filling",
      description: "Bite-sized cocktail samosas with an audible shatter crust, stuffed with savory roasted moong gram, cumin, and cracked black pepper.",
      highlights: ["Double Crispy Crust", "Slow-Roasted Spices", "Fresh Sealed Tub"],
      ingredients: ["Fine Flour", "Moong Gram", "Cold-Pressed Oil", "Roasted Cumin", "Asafoetida"],
      calories: "115 kcal / 3 pcs",
    },
    {
      id: "savory-spiral-murukku",
      name: "Traditional Spiral Murukku",
      category: "savory-snacks",
      categoryName: "Savory Snacks",
      badge: "South Indian Classic",
      weight: "200g Tub",
      price: "₹140",
      image: "/products/savory-spiral-murukku.jpg",
      tagline: "Crisp Hand-Pressed Rice Flour Spirals",
      description: "Golden spiral murukku pressed into delicate coils and fried until light, crisp, and deeply aromatic with roasted cumin and sesame.",
      highlights: ["Rice Flour Crisp", "Hand-Pressed Spirals", "Fresh Sealed Tub"],
      ingredients: ["Rice Flour", "Urad Dal Flour", "Sesame Seeds", "Cold-Pressed Oil", "Cumin"],
      calories: "135 kcal / 30g",
    },
    {
      id: "savory-crunchy-ring-murukku",
      name: "Crunchy Ring Murukku (Kodubale)",
      category: "savory-snacks",
      categoryName: "Savory Snacks",
      badge: "Traditional Crisp",
      weight: "200g Tub",
      price: "₹140",
      image: "/products/savory-crunchy-ring-murukku.jpg",
      tagline: "Spiced Golden Ring Crunch with Toasted Sesame",
      description: "Traditional ring-shaped crunchy savory snack seasoned with roasted cumin, red chili, and black sesame in a sealed clear tub.",
      highlights: ["Ring Crunch", "Black Sesame", "Fresh Sealed Tub"],
      ingredients: ["Rice Flour", "Roasted Gram", "Black Sesame", "Chili", "Cold-Pressed Oil"],
      calories: "130 kcal / 30g",
    },
    {
      id: "savory-ribbon-pakoda",
      name: "Crispy Ribbon Pakoda",
      category: "savory-snacks",
      categoryName: "Savory Snacks",
      badge: "Crispy Favorite",
      weight: "200g Tub",
      price: "₹135",
      image: "/products/savory-ribbon-pakoda.jpg",
      tagline: "Golden Gram Flour Ribbons with Black Sesame",
      description: "Thin, ridged ribbons of seasoned gram flour fried to a light golden crisp, finished with toasted black sesame for a fragrant bite.",
      highlights: ["Ridged Golden Texture", "Black Sesame", "Fresh Sealed Tub"],
      ingredients: ["Bengal Gram Flour", "Rice Flour", "Black Sesame", "Chili", "Asafoetida"],
      calories: "140 kcal / 30g",
    },
  ],

  "coconut-macaroons": [
    {
      id: "amber-coconut-macaroons",
      name: "Crisp Amber Coconut Macaroons",
      category: "coconut-macaroons",
      categoryName: "Coconut Macaroons",
      badge: "Heritage Specialty",
      weight: "200g Pack",
      price: "₹175",
      image: "/categories/coconut-macaroons.jpg",
      tagline: "Sun-Dried Coconut Shreds & Meringue Crisp",
      description: "Signature coastal recipe: finely shredded fresh coconut folded into light egg white meringue and baked until the tips turn caramelized amber.",
      highlights: ["Coastal Coconuts", "Crisp Outer Shell", "Chewy Center"],
      ingredients: ["Desiccated Coconut", "Pasture Egg Whites", "Pure Cane Sugar", "Madagascar Vanilla"],
      calories: "125 kcal / piece",
    },
    {
      id: "toasted-coconut-butter-drops",
      name: "Toasted Coconut Butter Drops",
      category: "coconut-macaroons",
      categoryName: "Coconut Macaroons",
      badge: "Tea Companion",
      weight: "250g Tin",
      price: "₹190",
      image: "/products/oatmeal-cookies.jpg",
      tagline: "Slow-Toasted Coconut Flakes & Cultured Butter",
      description: "Rich, golden drops packed with slow-toasted coconut chips and churned dairy butter for an intoxicating tropical aroma.",
      highlights: ["Toasted Coconut Flakes", "Cultured Butter", "Golden Crisp"],
      ingredients: ["Toasted Coconut", "Normandy Butter", "Wheat Flour", "Raw Sugar"],
      calories: "135 kcal / 2 pcs",
    },
  ],

  "viennoiserie": [
    {
      id: "signature-croissant",
      name: "Signature 27-Layer Croissants",
      category: "viennoiserie",
      categoryName: "Haute Viennoiserie",
      badge: "Atelier Signature",
      weight: "Single (90g)",
      price: "₹190",
      image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=900&auto=format&fit=crop",
      tagline: "Normandy AOP Butter Honeycomb Crumb",
      description: "Hand-rolled with Normandy AOP cultured butter, featuring 27 micro-layers of paper-thin honeycomb crumb and an audible shatter crust.",
      highlights: ["27 Micro Layers", "AOP Normandy Butter", "Wild Levain"],
      ingredients: ["AOP Charentes-Poitou Butter", "T55 Flour", "Guérande Sea Salt", "Wild Levain"],
      calories: "290 kcal",
    },
    {
      id: "valrhona-pain-au-chocolat",
      name: "Valrhona Noir 70% Pain au Chocolat",
      category: "viennoiserie",
      categoryName: "Haute Viennoiserie",
      badge: "Best Seller",
      weight: "Single (100g)",
      price: "₹210",
      image: "https://images.unsplash.com/photo-1549903072-7e6e0bedb7fb?q=80&w=900&auto=format&fit=crop",
      tagline: "Double Batons of 70% Dark Guanaja Chocolate",
      description: "Double batons of 70% dark Guanaja Valrhona chocolate enveloped in buttery laminated brioche dough, dusted with bittersweet Dutch cacao.",
      highlights: ["70% Valrhona Dark", "Laminated Brioche", "Bittersweet Cacao"],
      ingredients: ["70% Valrhona Guanaja", "Brioche Dough", "Bourbon Vanilla"],
      calories: "340 kcal",
    },
  ],

  "breads-and-bakery": [
    {
      id: "bb-classic-sliced-white-loaf",
      name: "Artisan Daily Sliced White Loaf Bread",
      category: "breads-and-bakery",
      categoryName: "Breads & Bakery",
      badge: "Daily Fresh Staple",
      weight: "400g / 800g Sliced Loaf",
      price: "₹60",
      image: "/products/artisan-sliced-white-loaf-bread.jpg",
      tagline: "Golden Hearth-Baked Soft Crust & Pillowy Crumb",
      description: "Masterfully baked daily white bread loaf served on an elegant porcelain platter with a delicate golden crust and an exceptionally soft, cloud-like crumb. Sliced uniformly for morning toast, sandwiches, and cafe paninis.",
      highlights: ["Daily Hearth Baked", "Super Soft Crumb", "Zero Trans Fats"],
      ingredients: ["Refined Wheat Flour", "Purified Water", "Live Baker's Yeast", "Pure Cane Sugar", "Dairy Butter"],
      calories: "75 kcal / slice",
    },
    {
      id: "bb-canto-rich-plum-cake",
      name: "Olene Canto Rich Spiced Plum Cake",
      category: "breads-and-bakery",
      categoryName: "Breads & Bakery",
      badge: "Celebration Reserve",
      weight: "500g Luxury Gift Box",
      price: "₹450",
      image: "/products/canto-rich-plum-cake-box.jpg",
      tagline: "Aged Dry Fruits, Roasted Cashews & Warm Winter Spices",
      description: "Our signature holiday masterpiece: a dark, luscious round plum cake packed with slow-soaked raisins, black currants, glazed cherries, and whole roasted cashews, presented with its bespoke Olene Canto matte black and gold gift box.",
      highlights: ["Luxury Matte Black Box", "Slow-Aged Fruits & Nuts", "Royal Festive Recipe"],
      ingredients: ["Aged California Raisins", "Black Currants", "Roasted Cashews", "Farm Butter", "Cinnamon & Nutmeg", "Caramelized Cane Sugar"],
      calories: "220 kcal / slice",
    },
    {
      id: "bb-hazelnut-chocolate-doughnuts",
      name: "Artisan Hazelnut Chocolate Brioche Doughnuts",
      category: "breads-and-bakery",
      categoryName: "Breads & Bakery",
      badge: "Artisan Bakery",
      weight: "2 Pcs Platter (180g)",
      price: "₹160",
      image: "/products/canto-hazelnut-chocolate-doughnuts.jpg",
      tagline: "Belgian Milk Chocolate Ganache & Roasted Hazelnut Crunch",
      description: "Two golden, pillow-soft brioche doughnuts served on an artisan wooden paddle board, generously filled with velvety cream and criss-crossed with rich Belgian chocolate ganache and roasted chopped hazelnuts.",
      highlights: ["Artisan Wooden Board", "Belgian Chocolate Ganache", "Crushed Toasted Hazelnuts"],
      ingredients: ["Brioche Flour", "Creamery Butter", "Belgian Milk Chocolate", "Roasted Hazelnuts", "Pasture Eggs", "Madagascar Vanilla"],
      calories: "210 kcal / doughnut",
    },
    {
      id: "bb-canto-heritage-fruit-cake-tin",
      name: "Olene Canto Heritage Rich Fruit Cake",
      category: "breads-and-bakery",
      categoryName: "Breads & Bakery",
      badge: "Collector's Tin",
      weight: "500g Sealed Keepsake Tin",
      price: "₹480",
      image: "/products/canto-heritage-fruit-cake-tin.jpg",
      tagline: "For a Healthier Slice of Your Life • Sealed Keepsake Tin",
      description: "A moist, aromatic celebration round cake packed with caramelized fruits and slow-infused spices, presented with our iconic collectible Olene Canto emerald green and gold embossed keepsake tin.",
      highlights: ["Signature Green Tin", "Slow-Caramelized Fruit Crumb", "Airtight Freshness Seal"],
      ingredients: ["Sun-Dried Raisins & Dates", "Spiced Fruit Extracts", "Pure Dairy Butter", "Demerara Sugar", "Stoneground Flour", "Cardamom & Cinnamon"],
      calories: "205 kcal / slice",
    },
    {
      id: "bb-golden-heart-shortbread-stack",
      name: "Classic Golden Heart Butter Shortbread Cookies",
      category: "breads-and-bakery",
      categoryName: "Breads & Bakery",
      badge: "Atelier Classic",
      weight: "300g Stack Pack",
      price: "₹210",
      image: "/products/canto-golden-heart-shortbread-stack.jpg",
      tagline: "100% Cultured Butter Heart-Cut Golden Shortbread",
      description: "A towering stack of golden-baked, melt-in-the-mouth heart shortbread cookies made with rich cultured creamery butter and cane sugar for the quintessential European tea-time indulgence.",
      highlights: ["100% Cultured Butter", "Iconic Heart Shape", "Melt-In-Mouth Crumb"],
      ingredients: ["Cultured Normandy Butter", "Fine Stoneground Wheat", "Raw Cane Sugar", "Pure Vanilla Extract", "Sea Salt"],
      calories: "135 kcal / cookie",
    },
    {
      id: "bb-honey-glazed-confectionery-doughnuts",
      name: "Twin Bowl Golden Honey-Glazed Doughnuts",
      category: "breads-and-bakery",
      categoryName: "Breads & Bakery",
      badge: "Tea-Time Treat",
      weight: "6 Pcs (300g Dual Bowl)",
      price: "₹190",
      image: "/products/golden-honey-glazed-doughnuts-bowls.jpg",
      tagline: "Wild Blossom Honey Glaze & Pillow-Soft Pastry Rounds",
      description: "Fluffy, golden-fried miniature ring doughnuts drenched in pure wild blossom honey glaze and served in dual black presentation bowls for an irresistible sweet crunch.",
      highlights: ["Pure Blossom Honey Glaze", "Dual Bowl Presentation", "Pillowy Soft Dough"],
      ingredients: ["Fine Wheat Flour", "Pure Blossom Honey", "Clarified Butter", "Farm Eggs", "Madagascar Vanilla", "Cane Sugar"],
      calories: "145 kcal / doughnut",
    },
    {
      id: "bb-canto-sealed-sweet-buns",
      name: "Olene Canto Sealed Soft Sweet Buns (Pack of 2)",
      category: "breads-and-bakery",
      categoryName: "Breads & Bakery",
      badge: "Retail Ready",
      weight: "Pack of 2 (160g)",
      price: "₹60",
      image: "/products/canto-sealed-sweet-buns-packet.jpg",
      tagline: "Soft, Smooth, Delicious • Ready To Eat Sealed Retail Pack",
      description: "Two bakery-fresh golden sweet buns individually sealed in signature Olene Canto airtight retail packaging. Wonderfully soft, fluffy, and lightly sweetened for breakfast or tea-time on the go.",
      highlights: ["Airtight Freshness Seal", "Ready to Eat", "Pillowy Soft Crumb"],
      ingredients: ["Enriched Wheat Flour", "Pure Creamery Butter", "Whole Milk Solids", "Live Baker's Yeast", "Cane Sugar"],
      calories: "160 kcal / bun",
    },
    {
      id: "bb-artisan-coconut-fruit-bun",
      name: "Artisan Coconut & Candied Fruit Sweet Bun",
      category: "breads-and-bakery",
      categoryName: "Breads & Bakery",
      badge: "Bakery Signature",
      weight: "Single (120g)",
      price: "₹50",
      image: "/products/canto-coconut-fruit-sweet-bun.jpg",
      tagline: "Toasted Coconut Shreds, Black Raisins, Glazed Cherries & Tutti-Frutti",
      description: "An iconic bakery-counter sweet bun baked to golden perfection, generously topped with sparkling sugar crystals, desiccated coconut shreds, plump dark raisins, red glazed cherries, and multicolored tutti-frutti.",
      highlights: ["Sparkling Sugar Crust", "Toasted Coconut & Fruits", "Melt-In-Mouth Sweet Dough"],
      ingredients: ["Enriched Wheat Flour", "Desiccated Coconut", "Dark Seedless Raisins", "Candied Fruit Drops (Tutti-Frutti)", "Glazed Cherries", "Pure Butter", "Cane Sugar"],
      calories: "210 kcal / bun",
    },
  ],

  "whiteloaf-snacks": [
    {
      id: "whiteloaf-ragi-murukku",
      name: "White Loaf Ragi Murukku",
      category: "whiteloaf-snacks",
      categoryName: "White Loaf Snacks",
      badge: "Healthy Crunch",
      weight: "150g Retail Pack",
      price: "₹65",
      image: "/products/whiteloaf-ragi-murukku.jpg",
      tagline: "Nutrient-Rich Finger Millet Savory Spirals",
      description: "Crunchy, earthy ragi murukku made with wholesome finger millet flour and fragrant spices, slow-fried for a light, guilt-free tea-time crunch.",
      highlights: ["Finger Millet (Ragi)", "Traditional Spices", "Fresh & Tasty Pack"],
      ingredients: ["Ragi Flour", "Rice Flour", "Roasted Cumin", "Cold-Pressed Oil", "Salt"],
      calories: "120 kcal / 30g",
    },
    {
      id: "whiteloaf-tomato-murukku",
      name: "White Loaf Tomato Murukku",
      category: "whiteloaf-snacks",
      categoryName: "White Loaf Snacks",
      badge: "Zesty Favorite",
      weight: "150g Retail Pack",
      price: "₹65",
      image: "/products/whiteloaf-tomato-murukku.jpg",
      tagline: "Zesty Tangy Tomato Flavored Crispy Sticks",
      description: "Crispy ridged murukku sticks seasoned with a tangy sun-ripened tomato spice blend. Royal taste for royal people!",
      highlights: ["Tangy Tomato Punch", "Crispy Ridged Texture", "Fresh & Tasty Pack"],
      ingredients: ["Rice Flour", "Tomato Seasoning", "Chili", "Cold-Pressed Oil", "Salt"],
      calories: "130 kcal / 30g",
    },
    {
      id: "whiteloaf-sweet-mixture",
      name: "White Loaf Sweet Mixture",
      category: "whiteloaf-snacks",
      categoryName: "White Loaf Snacks",
      badge: "Sweet & Savory",
      weight: "150g Retail Pack",
      price: "₹70",
      image: "/products/whiteloaf-sweet-mixture.jpg",
      tagline: "Golden Crispy Sev, Boondi, Poha & Candied Crunch",
      description: "A delightful sweet-savory medley of crispy sev, golden boondi, crunchy roasted nuts, raisins, and puffed poha flakes.",
      highlights: ["Sweet & Savory Balance", "Roasted Nuts & Raisins", "Fresh & Tasty Pack"],
      ingredients: ["Gram Flour Sev", "Puffed Rice (Poha)", "Roasted Peanuts", "Raisins", "Sugar", "Spices"],
      calories: "140 kcal / 30g",
    },
    {
      id: "whiteloaf-ragi-mixture",
      name: "White Loaf Ragi Mixture",
      category: "whiteloaf-snacks",
      categoryName: "White Loaf Snacks",
      badge: "Millet Special",
      weight: "150g Retail Pack",
      price: "₹70",
      image: "/products/whiteloaf-ragi-mixture.jpg",
      tagline: "Spiced Ragi Sev with Roasted Peanuts & Fried Dal",
      description: "Wholesome tea-time mixture starring crisp ragi sev strands tossed with roasted crunchy peanuts, fried lentils, and fresh curry leaves.",
      highlights: ["Crisp Ragi Sev", "Roasted Peanuts & Curry Leaves", "Fresh & Tasty Pack"],
      ingredients: ["Ragi Sev", "Fried Chana Dal", "Roasted Peanuts", "Curry Leaves", "Chili Spices"],
      calories: "135 kcal / 30g",
    },
    {
      id: "whiteloaf-onion-murukku",
      name: "White Loaf Onion Murukku",
      category: "whiteloaf-snacks",
      categoryName: "White Loaf Snacks",
      badge: "Savory Bite",
      weight: "150g Retail Pack",
      price: "₹65",
      image: "/products/whiteloaf-onion-murukku.jpg",
      tagline: "Crunchy Spiced Onion-Flavored Murukku Bites",
      description: "Crispy ridged murukku cylinders infused with aromatic shallots, roasted spices, and classic coastal seasonings. Fresh & tasty tea-time crunch.",
      highlights: ["Infused with Real Onions", "Ridged Crunchy Texture", "Fresh & Tasty Pack"],
      ingredients: ["Rice Flour", "Onion Essence & Flakes", "Cold-Pressed Oil", "Chili", "Salt"],
      calories: "130 kcal / 30g",
    },
    {
      id: "whiteloaf-pudina-mixture",
      name: "White Loaf Pudina Mixture",
      category: "whiteloaf-snacks",
      categoryName: "White Loaf Snacks",
      badge: "Herbal Fresh",
      weight: "150g Retail Pack",
      price: "₹70",
      image: "/products/whiteloaf-pudina-mixture.jpg",
      tagline: "Zesty Mint-Infused Sev with Crunchy Peanuts & Dal",
      description: "Refreshing, herb-infused tea mixture starring crisp mint (pudina) sev tossed with roasted peanuts, fried lentils, and aromatic seasoning.",
      highlights: ["Fresh Pudina (Mint) Flavor", "Roasted Peanuts & Dal", "Fresh & Tasty Pack"],
      ingredients: ["Gram Flour (Besan)", "Mint Herb Extract", "Peanuts", "Chana Dal", "Spices", "Oil", "Salt"],
      calories: "135 kcal / 30g",
    },
    {
      id: "whiteloaf-potato-chilli",
      name: "White Loaf Potato Chilli",
      category: "whiteloaf-snacks",
      categoryName: "White Loaf Snacks",
      badge: "Spicy Crunch",
      weight: "150g Retail Pack",
      price: "₹75",
      image: "/products/whiteloaf-potato-chilli.jpg",
      tagline: "Crispy Spiced Potato Sticks with Red Chilli Punch",
      description: "Matchstick-cut crunchy potato crisps tossed in fiery red chilli spices, salt, and herbs. An addictive tea-time and party favorite.",
      highlights: ["Crispy Potato Sticks", "Fiery Red Chilli Blend", "Fresh & Tasty Pack"],
      ingredients: ["Fresh Potatoes", "Edible Vegetable Oil", "Red Chilli Powder", "Dry Mango Amchur", "Salt"],
      calories: "145 kcal / 30g",
    },
    {
      id: "whiteloaf-butter-murukku",
      name: "White Loaf Butter Murukku",
      category: "whiteloaf-snacks",
      categoryName: "White Loaf Snacks",
      badge: "Royal Special",
      weight: "150g Retail Pack",
      price: "₹65",
      image: "/products/whiteloaf-butter-murukku.jpg",
      tagline: "Melt-in-Mouth Golden Spiral Butter Murukku",
      description: "Classic golden spiral murukku coils made with rich creamery butter and roasted cumin. Royal taste for royal people!",
      highlights: ["Pure Creamery Butter", "Melt-in-Mouth Flakiness", "Royal Taste for Royal People"],
      ingredients: ["Rice Flour", "Pure Butter", "Roasted Gram Flour", "Cumin Seeds", "Sesame", "Salt"],
      calories: "140 kcal / 30g",
    },
    {
      id: "whiteloaf-potato-mixture-spicy",
      name: "White Loaf Potato Mixture Spicy",
      category: "whiteloaf-snacks",
      categoryName: "White Loaf Snacks",
      badge: "Spicy Mixture",
      weight: "150g Retail Pack",
      price: "₹75",
      image: "/products/whiteloaf-potato-mixture-spicy.jpg",
      tagline: "Potato Straws, Roasted Peanuts & Curry Leaves in Spicy Seasoning",
      description: "Crispy spiced potato straws mingled with crunchy golden peanuts, fried curry leaves, and a kick of traditional red chili. Royal taste for royal people!",
      highlights: ["Crisp Potato Straws", "Roasted Peanuts & Curry Leaves", "Royal Taste for Royal People"],
      ingredients: ["Potato Straws", "Peanuts", "Curry Leaves", "Chili Powder", "Black Salt", "Oil"],
      calories: "145 kcal / 30g",
    },
    {
      id: "whiteloaf-nice-murukku",
      name: "White Loaf Nice Murukku",
      category: "whiteloaf-snacks",
      categoryName: "White Loaf Snacks",
      badge: "Royal Crunch",
      weight: "150g Retail Pack",
      price: "₹65",
      image: "/products/whiteloaf-nice-murukku.jpg",
      tagline: "Delicate Golden Spiral Rice Flour Murukku",
      description: "Thin, crunchy spiral murukku coils made from finely stoneground rice and roasted gram flour seasoned with fragrant cumin. Royal taste for royal people!",
      highlights: ["Delicate Thin Rings", "Roasted Cumin & Sesame", "Royal Taste for Royal People"],
      ingredients: ["Rice Flour", "Roasted Gram Flour", "Cumin Seeds", "Sesame Seeds", "Cold-Pressed Oil", "Salt"],
      calories: "130 kcal / 30g",
    },
    {
      id: "whiteloaf-pakkavada",
      name: "White Loaf Pakkavada",
      category: "whiteloaf-snacks",
      categoryName: "White Loaf Snacks",
      badge: "Authentic Ribbon",
      weight: "150g Retail Pack",
      price: "₹65",
      image: "/products/whiteloaf-pakkavada.jpg",
      tagline: "Crispy Golden Ribbon Cuts with Curry Leaves & Chili",
      description: "Classic crispy golden ribbon pakoda crisps crafted from pure gram flour and aromatic spices. Crisp, flaky, and addictive. Royal taste for royal people!",
      highlights: ["Crispy Ribbon Strips", "Aromatic Spiced Crunch", "Royal Taste for Royal People"],
      ingredients: ["Bengal Gram Flour (Besan)", "Rice Flour", "Chili Powder", "Asafoetida", "Curry Leaves", "Oil", "Salt"],
      calories: "135 kcal / 30g",
    },
    {
      id: "whiteloaf-masala-thatta",
      name: "White Loaf Masala Thatta",
      category: "whiteloaf-snacks",
      categoryName: "White Loaf Snacks",
      badge: "Crispy Thattai",
      weight: "150g Retail Pack",
      price: "₹70",
      image: "/products/whiteloaf-masala-thatta.jpg",
      tagline: "Spiced Round Rice Crackers with Roasted Gram & Crushed Pepper",
      description: "Thin and extremely crunchy round rice crisps seasoned with cracked black pepper, red chili, and roasted Bengal gram. Fresh & tasty tea-time companion.",
      highlights: ["Traditional Masala Thattai", "Cracked Black Pepper", "Fresh & Tasty Pack"],
      ingredients: ["Rice Flour", "Urad Dal Flour", "Roasted Chana Dal", "Black Pepper", "Red Chili", "Curry Leaves", "Salt"],
      calories: "135 kcal / 30g",
    },
    {
      id: "whiteloaf-ring-murukku",
      name: "White Loaf Ring Murukku",
      category: "whiteloaf-snacks",
      categoryName: "White Loaf Snacks",
      badge: "Ring Murukku",
      weight: "150g Retail Pack",
      price: "₹65",
      image: "/products/whiteloaf-ring-murukku.jpg",
      tagline: "Crispy Golden Circular Murukku Rings (Kodubale)",
      description: "Savory circular ring murukku hoops with a golden-brown crunch, infused with carom seeds and dried red chili. Royal taste for royal people!",
      highlights: ["Golden Ring Murukku", "Carom (Ajwain) & Cumin", "Royal Taste for Royal People"],
      ingredients: ["Rice Flour", "Roasted Gram Flour", "Ajwain Seeds", "Chili Flakes", "Edible Oil", "Salt"],
      calories: "135 kcal / 30g",
    },
    {
      id: "whiteloaf-masala-cheeda",
      name: "White Loaf Masala Cheeda",
      category: "whiteloaf-snacks",
      categoryName: "White Loaf Snacks",
      badge: "Spiced Cheeda",
      weight: "150g Retail Pack",
      price: "₹70",
      image: "/products/whiteloaf-masala-cheeda.jpg",
      tagline: "Hollow Crispy Grooved Cheeda Bites in Masala Seasoning",
      description: "Bite-sized grooved savory cylinders slow-fried to airy crispness and tossed in tangy coastal chatpata masala. Royal taste for royal people!",
      highlights: ["Hollow Grooved Texture", "Chatpata Masala Punch", "Royal Taste for Royal People"],
      ingredients: ["Rice Flour", "Urad Dal", "Sesame Seeds", "Black Pepper", "Chili Spice Mix", "Salt"],
      calories: "130 kcal / 30g",
    },
  ],
  "whiteloaf-cookies": [
    {
      id: "whiteloaf-nutty-buddy-cookies",
      name: "White Loaf Nutty Buddy Cookies",
      category: "whiteloaf-cookies",
      categoryName: "White Loaf Cookies",
      badge: "Nutty Delight",
      weight: "350g Premium Tin Can",
      price: "₹240",
      image: "/products/whiteloaf-nutty-buddy-cookies.jpg",
      tagline: "Golden Butter Cookies Studded with Roasted Cashews & Fruit Nuggets",
      description: "Generously studded with oven-roasted cashews, almonds, and candied fruit gems. Packed in an airtight premium tin to keep every crunchy bite fresh forever.",
      highlights: ["Roasted Cashews & Almonds", "A Taste to Remember Forever", "Airtight Keepsake Tin Can"],
      ingredients: ["Fine Wheat Flour", "Pure Butter", "Roasted Cashews", "California Almonds", "Candied Fruit Bits", "Cane Sugar", "Vanilla Infusion"],
      calories: "145 kcal / 2 pcs",
    },
    {
      id: "whiteloaf-curry-leaf-cookies",
      name: "White Loaf Curry Leaf Cookies",
      category: "whiteloaf-cookies",
      categoryName: "White Loaf Cookies",
      badge: "Savory Bestseller",
      weight: "350g Premium Tin Can",
      price: "₹220",
      image: "/products/whiteloaf-curry-leaf-cookies.jpg",
      tagline: "Aromatic South-Indian Herb Spiced Fluted Butter Cookies",
      description: "A distinctive savory-sweet innovation featuring aromatic fresh curry leaf flecks, subtle green chilies, and creamy cultured butter. Crisp and fragrant.",
      highlights: ["Fresh Garden Curry Leaves", "Savory-Sweet Fusion", "ISO & HACCP Certified Quality"],
      ingredients: ["Wheat Flour", "Cultured Butter", "Fresh Curry Leaves", "Mild Green Chilli", "Cumin", "Sea Salt", "Raw Cane Sugar"],
      calories: "135 kcal / 2 pcs",
    },
    {
      id: "whiteloaf-masala-cookies",
      name: "White Loaf Masala Cookies",
      category: "whiteloaf-cookies",
      categoryName: "White Loaf Cookies",
      badge: "Spicy Crunchy",
      weight: "350g Premium Tin Can",
      price: "₹220",
      image: "/products/whiteloaf-masala-cookies.jpg",
      tagline: "Cracked Black Pepper, Cumin & Toasted Sesame Spiced Biscuits",
      description: "Old-fashioned bakery masala biscuits crafted with stoneground whole wheat, crushed black peppercorns, roasted cumin, and nutty toasted sesame.",
      highlights: ["Roasted Cumin & Black Pepper", "Toasted Sesame Crust", "Traditional Tea-Time Biscuit"],
      ingredients: ["Whole Wheat Flour", "Pure Butter", "Black Peppercorns", "Roasted Cumin", "Sesame Seeds", "Spices", "Salt"],
      calories: "140 kcal / 2 pcs",
    },
    {
      id: "whiteloaf-oats-cookies",
      name: "White Loaf Oats Cookies",
      category: "whiteloaf-cookies",
      categoryName: "White Loaf Cookies",
      badge: "Wholesome Fiber",
      weight: "350g Premium Tin Can",
      price: "₹230",
      image: "/products/whiteloaf-oats-cookies.jpg",
      tagline: "Hearty Rolled Oats, Blossom Honey & Butter Crisp Bakes",
      description: "Packed with whole grain rolled oats, wild blossom honey, and golden butter for a satisfying, fibrous, and golden-crisp tea-time companion.",
      highlights: ["100% Rolled Whole Oats", "Rich in Dietary Fiber", "Wholesome Goodness in Every Bite"],
      ingredients: ["Rolled Oats", "Stoneground Whole Wheat", "Pure Butter", "Blossom Honey", "Brown Cane Sugar", "Baking Soda", "Cinnamon"],
      calories: "130 kcal / 2 pcs",
    },
    {
      id: "whiteloaf-ghee-cookies",
      name: "White Loaf Ghee Cookies",
      category: "whiteloaf-cookies",
      categoryName: "White Loaf Cookies",
      badge: "100% Desi Ghee",
      weight: "350g Premium Tin Can",
      price: "₹250",
      image: "/products/whiteloaf-ghee-cookies.jpg",
      tagline: "Melt-in-the-Mouth Traditional Pure Cow Ghee Shortbread",
      description: "Slow-baked with 100% pure fragrant desi cow ghee and cardamom, producing a delicately ridged golden shortbread that melts effortlessly on the tongue.",
      highlights: ["100% Pure Desi Cow Ghee", "Melt-In-Mouth Texture", "Cardamom Aroma"],
      ingredients: ["Fine Flour", "Pure Desi Cow Ghee", "Cardamom Essence", "Icing Sugar", "Baking Powder"],
      calories: "150 kcal / 2 pcs",
    },
    {
      id: "whiteloaf-american-gold-cookies",
      name: "White Loaf American Gold Cookies",
      category: "whiteloaf-cookies",
      categoryName: "White Loaf Cookies",
      badge: "Golden Crunch",
      weight: "350g Premium Tin Can",
      price: "₹250",
      image: "/products/whiteloaf-american-gold-cookies.jpg",
      tagline: "Crispy Golden Chunky Cookies Studded with Crushed Roasted Nuts",
      description: "American-style golden crisp butter cookies loaded with crushed roasted almonds, cashews, and rich butter vanilla aroma. Packed in a signature teal airtight tin.",
      highlights: ["Roasted Almond & Cashew Bits", "Signature American Gold Recipe", "Airtight Keepsake Tin Can"],
      ingredients: ["Fine Wheat Flour", "Pure Cultured Butter", "Crushed Roasted Almonds", "Cashews", "Golden Cane Sugar", "Bourbon Vanilla", "Sea Salt"],
      calories: "145 kcal / 2 pcs",
    },
    {
      id: "whiteloaf-butter-salt-cookies",
      name: "White Loaf Butter Salt Cookies",
      category: "whiteloaf-cookies",
      categoryName: "White Loaf Cookies",
      badge: "Sweet & Salty",
      weight: "350g Premium Tin Can",
      price: "₹220",
      image: "/products/whiteloaf-butter-salt-cookies.jpg",
      tagline: "Delicate Golden Shortbread with a Touch of Sea Salt Crystals",
      description: "Melt-in-mouth golden shortbread biscuits dock-pricked and delicately balanced with mineral-rich sea salt and rich sweet cream butter. An addictive tea companion.",
      highlights: ["Sweet & Salty Flavour Balance", "Melt-In-Mouth Shortbread", "A Taste to Remember Forever"],
      ingredients: ["Fine Wheat Flour", "Sweet Cream Butter", "Mineral Sea Salt", "Raw Cane Sugar", "Natural Vanilla"],
      calories: "135 kcal / 2 pcs",
    },
    {
      id: "whiteloaf-choco-chip-cookies",
      name: "White Loaf Choco Chip Cookies",
      category: "whiteloaf-cookies",
      categoryName: "White Loaf Cookies",
      badge: "Double Chocolate",
      weight: "350g Premium Tin Can",
      price: "₹250",
      image: "/products/whiteloaf-choco-chip-cookies.jpg",
      tagline: "Golden Butter Cookies Overflowing with Decadent Dark Chocolate Chips",
      description: "Loaded with premium dark chocolate chips that melt slightly with every bite. Baked to golden perfection with sweet butter for chocolate lovers of all ages.",
      highlights: ["Rich Dark Chocolate Chips", "Golden Butter Crumb", "Taste the Joy of Every Bite"],
      ingredients: ["Fine Wheat Flour", "Pure Butter", "Dark Chocolate Chips (55% Cacao)", "Brown Sugar", "Vanilla Extract", "Baking Soda", "Sea Salt"],
      calories: "150 kcal / 2 pcs",
    },
  ],
  "whiteloaf-boxes": [
    {
      id: "whiteloaf-premium-mixed-sweets-box",
      name: "White Loaf Premium Mixed Sweets Box",
      category: "whiteloaf-boxes",
      categoryName: "White Loaf Boxes",
      badge: "Luxury Reserve",
      weight: "1 Kg Luxury Gift Box",
      price: "₹850",
      image: "/products/whiteloaf-premium-mixed-sweets-box.jpg",
      tagline: "Signature Black & Gold Keepsake Box with Assorted Royal Mithai",
      description: "The pinnacle of celebration gifting. Elegantly presented in our signature black-and-gold geometric keepsake box, featuring an assortment of royal cashew katlis, badam bites, pure ghee pedas, and dry fruit confections.",
      highlights: ["Black & Gold Luxury Gift Box", "Assorted Royal Dry Fruit Mithai", "The Heavenly Source of Happiness"],
      ingredients: ["Pure Cow Ghee", "California Almonds", "Cashew Nuts", "Mawa Khoya", "Pistachio", "Saffron", "Cardamom"],
      calories: "380 kcal / 100g",
    },
    {
      id: "whiteloaf-royal-mixed-sweets-box",
      name: "White Loaf Royal Mixed Sweets Box",
      category: "whiteloaf-boxes",
      categoryName: "White Loaf Boxes",
      badge: "Festive Gold",
      weight: "1 Kg Festive Box",
      price: "₹750",
      image: "/products/whiteloaf-royal-mixed-sweets-box.jpg",
      tagline: "Royal Crimson Red & Gold Festive Gift Box with Assorted Sweets",
      description: "A grand festive celebration box in crimson red with gold filigree grid detailing, filled with traditional ghee mithai, handcrafted laddoos, and layered barfis crafted for joyful family occasions.",
      highlights: ["Crimson Red & Gold Gift Box", "Handcrafted Festive Mithai Assortment", "ISO Certified Clean Facility"],
      ingredients: ["Pure Desi Ghee", "Whole Milk Mawa", "Gram Flour", "Cashews", "Cardamom", "Sugar", "Silver Vark"],
      calories: "390 kcal / 100g",
    },
    {
      id: "whiteloaf-milk-sweets-box",
      name: "White Loaf Milk Sweets Box",
      category: "whiteloaf-boxes",
      categoryName: "White Loaf Boxes",
      badge: "Pure Mawa",
      weight: "1 Kg Celebration Box",
      price: "₹680",
      image: "/products/whiteloaf-milk-sweets-box.jpg",
      tagline: "Royal Sapphire Blue Box of Rich Khoya & Condensed Milk Delights",
      description: "A celebration of pure dairy heritage presented in a sapphire blue diamond-lattice box. Filled with silky pedas, mawa rolls, kesar barfi, and milk confections that melt softly in the mouth.",
      highlights: ["Royal Sapphire Blue Box", "100% Pure Milk & Khoya", "A Bite of a Moment of Delight"],
      ingredients: ["Fresh Cow Milk Khoya", "Condensed Milk", "Kesar Saffron", "Cardamom", "Pistachio Slivers", "Cane Sugar"],
      calories: "365 kcal / 100g",
    },
    {
      id: "whiteloaf-mixed-sweets-box",
      name: "White Loaf Mixed Sweets Box",
      category: "whiteloaf-boxes",
      categoryName: "White Loaf Boxes",
      badge: "Celebration Classic",
      weight: "1 Kg Classic Box",
      price: "₹650",
      image: "/products/whiteloaf-mixed-sweets-box.jpg",
      tagline: "Golden Sunburst Box with Everyday Joyful Traditional Sweets",
      description: "Bright, welcoming golden gift box packed with all-time Indian favorites: motichoor ladoos, Mysore pak, milk cakes, and coconut burfis for all festivals and corporate gifting.",
      highlights: ["Warm Golden Gift Packaging", "Traditional Ghee & Gram Flour Sweets", "HACCP Certified Quality"],
      ingredients: ["Pure Ghee", "Gram Flour (Besan)", "Sugar", "Fresh Milk", "Cardamom", "Dry Fruits"],
      calories: "375 kcal / 100g",
    },
    {
      id: "whiteloaf-mixed-halwa-tub",
      name: "White Loaf Kozhikodan Mixed Halwa Tub",
      category: "whiteloaf-boxes",
      categoryName: "White Loaf Boxes",
      badge: "Kerala Authentic",
      weight: "500g Fresh Sealed Tub",
      price: "₹150",
      image: "/products/whiteloaf-mixed-halwa-tub.jpg",
      tagline: "Authentic Malabar Kozhikodan Mixed Halwa Cubes in Clear Tub",
      description: "Legendary tender, chewy Malabar halwa cubes crafted with wheat flour, liquid glucose, and cardamom in vibrant fruit and spice varieties. Authentic Kozhikodan tradition from Olene Foods Manjeri.",
      highlights: ["Authentic Kozhikodan Recipe", "Assorted Colorful Halwa Cubes", "Manufactured in Manjeri, Kerala"],
      ingredients: ["Wheat Flour", "Liquid Glucose", "Water", "Cardamom", "Corn Flour", "Sugar", "Lemon", "Salt", "Edible Oil"],
      calories: "402 kcal / 100g",
    },
    {
      id: "whiteloaf-milk-peda-box",
      name: "White Loaf Milk Peda Box & Tray",
      category: "whiteloaf-boxes",
      categoryName: "White Loaf Boxes",
      badge: "Pure Khoya Peda",
      weight: "500g Sealed Tray & Presentation Box",
      price: "₹360",
      image: "/products/whiteloaf-milk-peda-box.jpg",
      tagline: "Embossed Traditional Khoya Pedas in Sealed Tray with Luxury Gift Box",
      description: "Handcrafted rich milk khoya pedas embossed with traditional floral motifs, sealed fresh in a food-grade presentation tray and packaged in an emerald green keepsake box.",
      highlights: ["100% Pure Milk Khoya", "Floral Embossed Traditional Pedas", "Sealed Tray & Luxury Box"],
      ingredients: ["Pure Milk Solids (Mawa/Khoya)", "Cane Sugar", "Cardamom", "Pistachio Essence", "Pure Ghee"],
      calories: "370 kcal / 100g",
    },
    {
      id: "whiteloaf-ghee-sweets-box",
      name: "White Loaf Ghee Sweets Box",
      category: "whiteloaf-boxes",
      categoryName: "White Loaf Boxes",
      badge: "100% Desi Ghee",
      weight: "1 Kg Festive Box",
      price: "₹720",
      image: "/products/whiteloaf-ghee-sweets-box.png",
      tagline: "Peach & Gold Lattice Box Packed with Rich Pure Desi Ghee Mithai",
      description: "An opulent coral peach and gold celebration box brimming with authentic desi ghee confections: Mysore pak, ghee barfis, and rich slow-roasted gram flour sweets.",
      highlights: ["100% Pure Desi Cow Ghee", "Festive Peach & Gold Keepsake Box", "HACCP & ISO Certified"],
      ingredients: ["Pure Desi Cow Ghee", "Gram Flour", "Cashews", "Saffron", "Cardamom", "Sugar"],
      calories: "395 kcal / 100g",
    },
    {
      id: "whiteloaf-laddu-box",
      name: "White Loaf Laddu Box & Tray",
      category: "whiteloaf-boxes",
      categoryName: "White Loaf Boxes",
      badge: "Desi Ghee Laddu",
      weight: "500g Sealed Tray & Presentation Box",
      price: "₹320",
      image: "/products/whiteloaf-laddu-box.jpg",
      tagline: "Golden Desi Ghee Boondi Laddus Garnished with Raisins & Cashews",
      description: "Mouth-watering golden boondi laddus crafted in pure desi ghee, crowned with plump golden raisins and crushed melon seeds. Sealed fresh in a presentation tray with a cheerful yellow gift box.",
      highlights: ["Pure Desi Ghee Boondi", "Golden Raisins & Cashew Garnish", "Sealed Tray Freshness"],
      ingredients: ["Gram Flour (Besan)", "Pure Cow Ghee", "Sugar Syrup", "Golden Raisins", "Cashews", "Cardamom"],
      calories: "385 kcal / 100g",
    },
    {
      id: "whiteloaf-fresh-jilebi-tray",
      name: "White Loaf Fresh Jilebi Tray",
      category: "whiteloaf-boxes",
      categoryName: "White Loaf Boxes",
      badge: "Crispy Juicy",
      weight: "400g Sealed Tray",
      price: "₹220",
      image: "/products/whiteloaf-fresh-jilebi-tray.jpg",
      tagline: "Golden Spiral Fermented Batter Jilebis Soaked in Saffron Sugar Syrup",
      description: "Crispy, coiled golden jilebis deep-fried to perfection and steeped in aromatic warm saffron-cardamom sugar syrup, packaged in a hygienic airtight presentation tray.",
      highlights: ["Crisp Shell & Juicy Core", "Pure Saffron & Cardamom Syrup", "Sealed Hygienic Tray"],
      ingredients: ["Fine Flour (Maida)", "Urad Dal", "Sugar Syrup", "Saffron", "Cardamom", "Vegetable Oil"],
      calories: "330 kcal / 100g",
    },
    {
      id: "whiteloaf-jilebi-box",
      name: "White Loaf Jilebi Gift Box",
      category: "whiteloaf-boxes",
      categoryName: "White Loaf Boxes",
      badge: "Celebration Gift",
      weight: "800g Festive Gift Box",
      price: "₹450",
      image: "/products/whiteloaf-jilebi-box.jpg",
      tagline: "Grand Burgundy & Gold Geometric Gift Box for Celebration Jilebi",
      description: "Festive confectionery box in rich burgundy red with golden lattice borders, designed to present fresh hot celebratory jilebis for weddings, poojas, and joyous gatherings.",
      highlights: ["Burgundy & Gold Gift Packaging", "Traditional Celebration Sweet", "The Heavenly Source of Happiness"],
      ingredients: ["Refined Wheat Flour", "Sugar", "Saffron Essence", "Pure Ghee / Oil", "Cardamom Infusion"],
      calories: "330 kcal / 100g",
    },
    {
      id: "whiteloaf-dates-roll-box",
      name: "White Loaf Dates Roll Box",
      category: "whiteloaf-boxes",
      categoryName: "White Loaf Boxes",
      badge: "Sugar-Free Health",
      weight: "1 Kg Luxury Gift Box",
      price: "₹780",
      image: "/products/whiteloaf-dates-roll-box.jpg",
      tagline: "Navy Blue & Gold Geometric Gift Box with Handcrafted Dry Fruit Dates Rolls",
      description: "Naturally sweetened with luscious Arabian dates, crushed cashews, almonds, and pistachios, rolled in crunchy poppy seeds. Elegantly packaged in our navy blue and gold celebration box.",
      highlights: ["Zero Refined Sugar", "Arabian Dates & Roasted Dry Fruits", "The Heavenly Source of Happiness"],
      ingredients: ["Arabian Dates", "Roasted Cashews", "California Almonds", "Pistachios", "Poppy Seeds (Khas Khas)", "Cardamom", "Pure Cow Ghee"],
      calories: "340 kcal / 100g",
    },
    {
      id: "whiteloaf-ghee-pak-box",
      name: "White Loaf Ghee Pak Box",
      category: "whiteloaf-boxes",
      categoryName: "White Loaf Boxes",
      badge: "Royal Mysore Ghee Pak",
      weight: "1 Kg Luxury Gift Box",
      price: "₹750",
      image: "/products/whiteloaf-ghee-pak-box.jpg",
      tagline: "Royal Purple & Gold Box with Melt-in-the-Mouth Traditional Pure Ghee Pak",
      description: "The classic heritage sweet of royalty. Slow-roasted gram flour blended with copious amounts of hot aromatic desi cow ghee to produce porous, melt-in-mouth golden fudge squares.",
      highlights: ["100% Pure Desi Cow Ghee", "Porous Melt-In-Mouth Texture", "ISO & HACCP Certified Facility"],
      ingredients: ["Pure Desi Cow Ghee", "Stoneground Gram Flour (Besan)", "Sugar Syrup", "Cardamom Essence"],
      calories: "440 kcal / 100g",
    },
    {
      id: "whiteloaf-badusha-box",
      name: "White Loaf Badusha Box & Tray",
      category: "whiteloaf-boxes",
      categoryName: "White Loaf Boxes",
      badge: "Flaky Balushahi",
      weight: "500g Sealed Tray & Presentation Box",
      price: "₹340",
      image: "/products/whiteloaf-badusha-box.jpg",
      tagline: "Flaky Glazed Golden Badushas in Sealed Tray with Festive Crimson Box",
      description: "Traditional flaky multi-layered flour doughnuts fried slowly in desi ghee and drenched in crystallizing cardamom sugar syrup. Sealed in a hygienic tray with an elegant maroon gift box.",
      highlights: ["Multi-Layered Flaky Crumb", "Cardamom Sugar Glaze", "Sealed Hygienic Freshness Tray"],
      ingredients: ["Fine Wheat Flour", "Pure Desi Ghee", "Sugar Syrup", "Curd", "Cardamom Powder", "Saffron"],
      calories: "375 kcal / 100g",
    },
    {
      id: "whiteloaf-fresh-dates-roll-tray",
      name: "White Loaf Fresh Dates Roll Tray",
      category: "whiteloaf-boxes",
      categoryName: "White Loaf Boxes",
      badge: "Nutrient Dense",
      weight: "500g Sealed Presentation Tray",
      price: "₹390",
      image: "/products/whiteloaf-fresh-dates-roll-tray.jpg",
      tagline: "Poppy-Crusted Soft Black Dates Cylinders Stuffed with Roasted Nuts",
      description: "Freshly prepared date confectionery rolls densely coated with toasted white poppy seeds (khas khas) and packed with whole roasted nuts. Sealed fresh in a clear presentation tray.",
      highlights: ["Toasted White Poppy Seed Crust", "Whole Roasted Nuts Inside", "Naturally Sweet & Wholesome"],
      ingredients: ["Pressed Black Dates", "Poppy Seeds", "Roasted Cashew Nuts", "Almonds", "Pure Ghee"],
      calories: "340 kcal / 100g",
    },
  ],
};

// Aliases to resolve various slug variations
export const SLUG_ALIASES = {
  "biscuits": "biscuit-and-cookies",
  "biscuit": "biscuit-and-cookies",
  "biscuit-and-cookies": "biscuit-and-cookies",
  "biscuits-and-cookies": "biscuit-and-cookies",
  "cookies": "biscuit-and-cookies",
  "sweet-and-mithai": "sweet-and-mithai",
  "sweets-and-mithai": "sweet-and-mithai",
  "sweet-mithai": "sweet-and-mithai",
  "sweets-mithai": "sweet-and-mithai",
  "sweet": "sweet-and-mithai",
  "sweets": "sweet-and-mithai",
  "mithai": "sweet-and-mithai",
  "mithais": "sweet-and-mithai",
  "heritage-sweets": "sweet-and-mithai",
  "heritage-sweet": "sweet-and-mithai",
  "biscuits-and-sweets": "biscuit-and-cookies",
  "savory": "savory-snacks",
  "savories": "savory-snacks",
  "savory-snacks": "savory-snacks",
  "traditional-savories": "savory-snacks",
  "macaroons": "coconut-macaroons",
  "coconut-macaroons": "coconut-macaroons",
  "viennoiserie": "viennoiserie",
  "croissants": "viennoiserie",
  "breads-and-bakery": "breads-and-bakery",
  "bread-and-bakery": "breads-and-bakery",
  "breads": "breads-and-bakery",
  "bread": "breads-and-bakery",
  "bakery": "breads-and-bakery",
  "white-loaf": "breads-and-bakery",
  "white-loaf-wholesale": "breads-and-bakery",
  "whiteloaf-snacks": "whiteloaf-snacks",
  "white-loaf-snacks": "whiteloaf-snacks",
  "whiteloaf": "whiteloaf-snacks",
  "whiteloaf-snack": "whiteloaf-snacks",
  "white-loaf-snack": "whiteloaf-snacks",
  "whiteloaf-cookies": "whiteloaf-cookies",
  "white-loaf-cookies": "whiteloaf-cookies",
  "whiteloaf-cookie": "whiteloaf-cookies",
  "white-loaf-cookie": "whiteloaf-cookies",
  "whiteloaf-boxes": "whiteloaf-boxes",
  "white-loaf-boxes": "whiteloaf-boxes",
  "whiteloaf-box": "whiteloaf-boxes",
  "white-loaf-box": "whiteloaf-boxes",
  "sweet-boxes": "whiteloaf-boxes",
  "boxes": "whiteloaf-boxes",
};

CATEGORY_PRODUCTS["heritage-sweets"] = CATEGORY_PRODUCTS["sweet-and-mithai"];
CATEGORY_PRODUCTS["white-loaf"] = CATEGORY_PRODUCTS["breads-and-bakery"];

export function getCategoryById(idOrSlug) {
  if (!idOrSlug) return null;
  const normalized = idOrSlug.toString().toLowerCase().trim();
  const canonicalId = SLUG_ALIASES[normalized] || normalized;
  return CATEGORIES_SHOWCASE.find((cat) => cat.id === canonicalId) || null;
}

export function getProductsByCategory(categoryIdOrSlug) {
  if (!categoryIdOrSlug) return [];
  const normalized = categoryIdOrSlug.toString().toLowerCase().trim();
  const canonicalId = SLUG_ALIASES[normalized] || normalized;
  return CATEGORY_PRODUCTS[canonicalId] || [];
}

export function getAllProducts() {
  return Object.values(CATEGORY_PRODUCTS).flat();
}
